### ISSUE TITLE
Un peu léger

### ISSUE THREAD

**Issue by Leafgard** [vicmij/Projet_2018_Ruche_Connecte#1]
En effet, je pense que le nom d'utilisateur `root` et le mot de passe ` ` sont un peu légers dans la partie Administration de votre [Site internet](http://www.branly.vicmij.fr/). Faites attention, quelqu'un pourrait ainsi impacter votre projet !

**Comment by vicmij** [comment]
Bonjour, il s'agit d'une petite erreur de ma part , merci de l'avoir confirmer.
